server:
  address: 127.0.0.1
  port: 8080
  error:
    include-message: never
    include-stacktrace: never

spring:
  application:
    name: polyglotmesh
  codec:
    max-in-memory-size: 128KB

polyglotmesh:
  execution:
    timeout-ms: 15000